# Stage 1: Build stage
FROM node:22.5.1 as builder

WORKDIR /usr/src/app

RUN npm install mysql2 --save && \
    npm install chance --save


# Stage 2: Production stage
FROM node:22.5.1-alpine

WORKDIR /usr/src/app

# Copy dependencies from the builder stage
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app .

EXPOSE 3000

CMD ["node", "/usr/src/app/server.js"]