version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    networks:
      - fullcycle-net
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  node:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    image: node:22.5.1-alpine
    container_name: node
    tty: true
    networks:
      - fullcycle-net
    expose:
      - "3000"
    volumes:
      - ./node:/usr/src/app
      - node-html:/usr/src/app/public
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx
    tty: true
    networks:
      - fullcycle-net
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - node-html:/usr/share/nginx/html
    depends_on:
      node:
        condition: service_healthy

networks:
  fullcycle-net:
    driver: bridge

volumes:
  node-html: